//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftUNI.WebAPI.Datos.Usuarios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuerysUsuarios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuerysUsuarios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftUNI.WebAPI.Datos.Usuarios.QuerysUsuarios", typeof(QuerysUsuarios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update usuario set matricula = @matricula where ID_Usuario=@id.
        /// </summary>
        internal static string ActualizarMatriculaUsuario {
            get {
                return ResourceManager.GetString("ActualizarMatriculaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE dbo.Usuario
        ///   SET
        ///
        ///      Telefono = @Telefono
        ///      ,Celular = @Celular      
        ///      ,Region = @Region
        ///      ,Provincia = @Provincia
        ///      ,Municipio = @Municipio
        ///      ,Sector = @Sector
        ///      ,Residencia = @Residencia
        /// WHERE  ID_Usuario = @id.
        /// </summary>
        internal static string ActualizarUsuario {
            get {
                return ResourceManager.GetString("ActualizarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///      Nombres
        ///      ,Apellidos
        ///      ,Identificacion
        ///      ,Telefono
        ///      ,Celular
        ///      ,Fecha_Nacimiento
        ///      ,Lugar_Nacimiento
        ///      ,Nacionalidad
        ///      ,Region
        ///      ,Provincia
        ///      ,Municipio
        ///      ,Sector
        ///      ,Residencia
        ///  FROM dbo.UsuarioDumy where Identificacion = @cedula.
        /// </summary>
        internal static string ConsultarInfoUsuarioDumy {
            get {
                return ResourceManager.GetString("ConsultarInfoUsuarioDumy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  ID_Usuario
        ///      ,Nombres
        ///      ,Apellidos
        ///      ,Identificacion
        ///      ,Correo
        ///      ,Clave
        ///      ,Telefono
        ///      ,Celular
        ///      ,Fecha_Nacimiento
        ///      ,Lugar_Nacimiento
        ///      ,Nacionalidad
        ///      ,Region
        ///      ,Provincia
        ///      ,Municipio
        ///      ,Sector
        ///      ,Residencia
        ///	  ,Matricula
        ///	  ,Tipo, Inscrito
        ///  FROM dbo.Usuario where ID_Usuario = @id.
        /// </summary>
        internal static string ConsultaUsuario {
            get {
                return ResourceManager.GetString("ConsultaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update dbo.Usuario set activo = &apos;false&apos; where ID_Usuario = @id.
        /// </summary>
        internal static string EliminarUsuario {
            get {
                return ResourceManager.GetString("EliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select max(matricula) Matricula from Matriculas.
        /// </summary>
        internal static string GenerarMatricula {
            get {
                return ResourceManager.GetString("GenerarMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Usuario set inscrito = &apos;true&apos; where id_usuario=@id.
        /// </summary>
        internal static string InscribirUsuario {
            get {
                return ResourceManager.GetString("InscribirUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Matriculas values(@matricula).
        /// </summary>
        internal static string InsertarMatricula {
            get {
                return ResourceManager.GetString("InsertarMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO dbo.Usuario
        ///           (
        ///				Nombres
        ///			   ,Apellidos
        ///			   ,Identificacion
        ///			   ,Correo
        ///			   ,Clave
        ///			   ,Fecha_Nacimiento
        ///			   ,Lugar_Nacimiento
        ///			   ,Nacionalidad
        ///			   ,Region
        ///			   ,Provincia
        ///			   ,Municipio
        ///			   ,Sector
        ///			   ,Residencia
        ///			   ,Tipo
        ///		  )
        ///     VALUES
        ///           (
        ///				@Nombre
        ///			   ,@Apellidos
        ///			   ,@Identificacion
        ///			   ,@Correo
        ///			   ,@Clave
        ///			   ,@Fecha_Nacimiento
        ///			   ,@Lugar_Nacimiento
        ///			   ,@Nacionalidad
        ///			   ,@Region
        ///			   ,@Pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertarUsuario {
            get {
                return ResourceManager.GetString("InsertarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  
        ///      Nombres
        ///      
        ///  FROM dbo.Usuario where Identificacion = @cedula and activo = &apos;true&apos;.
        /// </summary>
        internal static string ValidaExisteUser {
            get {
                return ResourceManager.GetString("ValidaExisteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  ID_Usuario
        ///      ,Nombres
        ///      ,Apellidos
        ///      ,Identificacion
        ///      ,Correo
        ///      ,Clave
        ///      ,Telefono
        ///      ,Celular
        ///      ,Fecha_Nacimiento
        ///      ,Lugar_Nacimiento
        ///      ,Nacionalidad
        ///      ,Region
        ///      ,Provincia
        ///      ,Municipio
        ///      ,Sector
        ///      ,Residencia,inscrito ,Matricula,tipo
        ///  FROM dbo.Usuario where (Correo = @user or Identificacion = @user) and clave = @clave and activo = &apos;true&apos;.
        /// </summary>
        internal static string ValidaLoginUsuario {
            get {
                return ResourceManager.GetString("ValidaLoginUsuario", resourceCulture);
            }
        }
    }
}
